services:
  mysql:
    image: mysql:5.7
    container_name: nacos-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nacos_config
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./init.d:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always

  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos-standalone-mysql
    depends_on:
      - mysql
    environment:
      - MODE=standalone
      - NACOS_AUTH_ENABLE=true
      - NACOS_AUTH_TOKEN=U2VjcmV0S2V5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5
      - NACOS_AUTH_IDENTITY_KEY=nacos
      - NACOS_AUTH_IDENTITY_VALUE=nacos
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=mysql
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_DB_NAME=nacos_config
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=root
    ports:
      - "8848:8848"
      - "10010:8080"
      - "9848:9848"
    restart: always

  etcd:
    image: quay.m.daocloud.io/coreos/etcd:v3.5.5
    container_name: milvus-etcd
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    command: >
      etcd
      -advertise-client-urls=http://0.0.0.0:2379
      -listen-client-urls=http://0.0.0.0:2379
      --data-dir /etcd
    volumes:
      - ./milvus-etcd:/etcd
    ports:
      - "2379:2379"
    restart: always

  minio:
    image: docker.m.daocloud.io/minio/minio:latest
    container_name: milvus-minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: minio server /minio-data --console-address ":9001"
    volumes:
      - ./milvus-minio:/minio-data
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: always

  milvus:
    image: docker.m.daocloud.io/milvusdb/milvus:v2.4.0
    container_name: milvus-standalone
    depends_on:
      - etcd
      - minio
    environment:
      - ETCD_ENDPOINTS=etcd:2379
      - MINIO_ADDRESS=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    command: ["milvus", "run", "standalone"]
    volumes:
      - ./milvus-data:/var/lib/milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    restart: always

  attu:
    image: zilliz/attu:latest
    container_name: attu
    depends_on:
      - milvus
    environment:
      - MILVUS_URL=milvus:19530
    ports:
      - "10020:3000"
    restart: always
