# Service Identity (used for Nacos registration)
service:
  name: "readify-eval"
  host: ""          # empty = auto-detect IP
  port: 8082

# Nacos Configuration
nacos:
  enabled: true
  server_addr: "localhost:8848"
  namespace: "ca5b6af9-5336-42f7-b68c-515779f79a98"
  group: "READIFY"
  username: "nacos"
  password: "nacos2025"
  cluster: "DEFAULT"
  heartbeat_interval: 5
  config_data_id: "readify-eval.yaml"
